version: '3.9'

services:
  chabot-app:
    build: .
    env_file:
      - .env
    environment:
      - HF_HOME=/workspace/hf_cache
    volumes:
      - "${HF_CACHE_DIR}:/workspace/hf_cache"
      - ./temp:/app/temp
    container_name: chatbot-service
    ports:
      - "5500:5500"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  qdrant_data: